Section "ServerFlags"
    Option "DontVTSwitch" "false"
    Option "AllowMouseOpenFail" "true"
EndSection

Section "InputClass"
    Identifier "All Keyboards"
    MatchIsKeyboard "on"
    Driver "evdev"
    Option "XkbLayout" "us"
EndSection

Section "InputClass"
    Identifier "All Pointers"
    MatchIsPointer "on"
    Driver "evdev"
EndSection

Section "Device"
    Identifier "GPU0"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "GPU0"
EndSection
