static const char HTTP_HTML[] =
  "<!DOCTYPE html>\n"
  "<html lang=\"en\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
  "<title>AI Linux</title>\n"
  "<style>\n"
  "*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}\n"
  ":root{\n"
  "  --bg:#0d1117;--surface:#161b22;--border:#30363d;\n"
  "  --text:#e6edf3;--dim:#8b949e;--accent:#58a6ff;\n"
  "  --green:#3fb950;--user-bg:#1f6feb;--red:#f85149;\n"
  "}\n"
  "body{background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;height:100vh;display:flex;flex-direction:column;overflow:hidden}\n"
  "header{background:var(--surface);border-bottom:1px solid var(--border);padding:13px 20px;display:flex;align-items:center;gap:10px;flex-shrink:0}\n"
  ".dot{width:9px;height:9px;border-radius:50%;background:var(--green);box-shadow:0 0 7px var(--green)}\n"
  "header h1{font-size:15px;font-weight:600;flex:1}\n"
  ".badge{font-size:11px;color:var(--dim);background:var(--bg);padding:3px 10px;border-radius:20px;border:1px solid var(--border)}\n"
  "#chat{flex:1;overflow-y:auto;padding:24px 20px;display:flex;flex-direction:column;gap:20px;scroll-behavior:smooth}\n"
  "#chat::-webkit-scrollbar{width:4px}\n"
  "#chat::-webkit-scrollbar-thumb{background:var(--border);border-radius:2px}\n"
  ".row{display:flex;flex-direction:column;gap:4px}\n"
  ".row.user{align-items:flex-end}\n"
  ".row.ai{align-items:flex-start}\n"
  ".lbl{font-size:11px;color:var(--dim);padding:0 4px}\n"
  ".bubble{max-width:78%;padding:12px 17px;border-radius:16px;line-height:1.65;font-size:14px;word-break:break-word}\n"
  ".row.user .bubble{background:var(--user-bg);color:#fff;border-bottom-right-radius:4px}\n"
  ".row.ai  .bubble{background:var(--surface);border:1px solid var(--border);border-bottom-left-radius:4px}\n"
  ".bubble strong{font-weight:600}\n"
  ".bubble em{font-style:italic;color:var(--dim)}\n"
  ".bubble code{background:var(--bg);padding:2px 6px;border-radius:4px;font-family:'SFMono-Regular',Consolas,monospace;font-size:12px;color:#ff7b72}\n"
  ".bubble pre{background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:14px;margin:10px 0;overflow-x:auto}\n"
  ".bubble pre code{background:none;padding:0;color:var(--text);font-size:13px;white-space:pre}\n"
  ".thinking{display:flex;align-items:center;gap:6px;padding:14px 18px;background:var(--surface);border:1px solid var(--border);border-radius:16px;border-bottom-left-radius:4px}\n"
  ".td{width:7px;height:7px;border-radius:50%;background:var(--accent);animation:blink 1.4s infinite ease-in-out}\n"
  ".td:nth-child(2){animation-delay:.2s}.td:nth-child(3){animation-delay:.4s}\n"
  "@keyframes blink{0%,80%,100%{transform:scale(.7);opacity:.4}40%{transform:scale(1);opacity:1}}\n"
  "#bar{background:var(--surface);border-top:1px solid var(--border);padding:15px 20px;display:flex;gap:10px;align-items:flex-end;flex-shrink:0}\n"
  "#inp{flex:1;background:var(--bg);border:1px solid var(--border);border-radius:10px;color:var(--text);padding:11px 15px;font-size:14px;font-family:inherit;resize:none;min-height:44px;max-height:140px;outline:none;transition:border-color .15s;line-height:1.5}\n"
  "#inp:focus{border-color:var(--accent)}\n"
  "#inp::placeholder{color:var(--dim)}\n"
  ".btn{background:var(--surface);border:1px solid var(--border);border-radius:10px;color:var(--text);cursor:pointer;width:44px;height:44px;font-size:18px;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:background .15s}\n"
  ".btn:hover{background:var(--border)}\n"
  ".btn:disabled{opacity:.4;cursor:not-allowed}\n"
  "#sbtn{background:var(--accent);border-color:var(--accent);color:#0d1117;font-size:16px;font-weight:700}\n"
  "#sbtn:hover:not(:disabled){background:#79c0ff;border-color:#79c0ff}\n"
  "#vbtn.rec{background:var(--red);border-color:var(--red);animation:breathe 1s infinite}\n"
  "@keyframes breathe{0%,100%{box-shadow:0 0 0 0 rgba(248,81,73,.5)}50%{box-shadow:0 0 0 8px rgba(248,81,73,0)}}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<header>\n"
  "  <div class=\"dot\" id=\"sdot\"></div>\n"
  "  <h1>AI Linux</h1>\n"
  "  <span class=\"badge\" id=\"bdg\">connecting...</span>\n"
  "</header>\n"
  "<div id=\"chat\">\n"
  "  <div class=\"row ai\">\n"
  "    <span class=\"lbl\">AI</span>\n"
  "    <div class=\"bubble\">Hello! I am your AI assistant with full control of this Linux system. I can run commands, install software, manage files, browse the web, and more. What would you like to do?</div>\n"
  "  </div>\n"
  "</div>\n"
  "<div id=\"bar\">\n"
  "  <textarea id=\"inp\" rows=\"1\" placeholder=\"Ask anything... (Enter to send, Shift+Enter for newline)\"></textarea>\n"
  "  <button class=\"btn\" id=\"vbtn\" title=\"Voice input\">&#127908;</button>\n"
  "  <button class=\"btn\" id=\"sbtn\" title=\"Send (Enter)\">&#10148;</button>\n"
  "</div>\n"
  "<script>\n"
  "var chat=document.getElementById('chat'),\n"
  "    inp=document.getElementById('inp'),\n"
  "    sbtn=document.getElementById('sbtn'),\n"
  "    vbtn=document.getElementById('vbtn'),\n"
  "    sdot=document.getElementById('sdot'),\n"
  "    bdg=document.getElementById('bdg');\n"
  "\n"
  "function setStatus(on){\n"
  "  sdot.style.background=on?'var(--green)':'var(--red)';\n"
  "  sdot.style.boxShadow=on?'0 0 7px var(--green)':'0 0 7px var(--red)';\n"
  "  bdg.textContent=on?'online':'offline';\n"
  "}\n"
  "\n"
  "fetch('/api/ping').then(function(){setStatus(true)}).catch(function(){setStatus(false)});\n"
  "\n"
  "var _rszTimer=null;\n"
  "inp.addEventListener('input',function(){\n"
  "  clearTimeout(_rszTimer);\n"
  "  _rszTimer=setTimeout(function(){\n"
  "    inp.style.height='auto';\n"
  "    inp.style.height=Math.min(inp.scrollHeight,140)+'px';\n"
  "  },50);\n"
  "});\n"
  "\n"
  "inp.addEventListener('keydown',function(e){\n"
  "  if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}\n"
  "});\n"
  "sbtn.addEventListener('click',send);\n"
  "\n"
  "function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
  "\n"
  "function md(t){\n"
  "  t=t.replace(/```([a-z]*)\\n?([\\s\\S]*?)```/g,function(_,l,c){return '<pre><code>'+esc(c.trim())+'</code></pre>';});\n"
  "  t=t.replace(/`([^`\\n]+)`/g,function(_,c){return '<code>'+esc(c)+'</code>';});\n"
  "  t=t.replace(/\\*\\*([^*]+)\\*\\*/g,'<strong>$1</strong>');\n"
  "  t=t.replace(/\\*([^*\\n]+)\\*/g,'<em>$1</em>');\n"
  "  t=t.replace(/\\n/g,'<br>');\n"
  "  return t;\n"
  "}\n"
  "\n"
  "function addRow(role,content,isHTML){\n"
  "  var row=document.createElement('div');row.className='row '+role;\n"
  "  var lbl=document.createElement('span');lbl.className='lbl';lbl.textContent=role==='user'?'You':'AI';\n"
  "  var bub=document.createElement('div');bub.className='bubble';\n"
  "  if(isHTML)bub.innerHTML=content;else bub.textContent=content;\n"
  "  row.appendChild(lbl);row.appendChild(bub);\n"
  "  chat.appendChild(row);chat.scrollTop=chat.scrollHeight;\n"
  "  return bub;\n"
  "}\n"
  "\n"
  "function showThink(){\n"
  "  var row=document.createElement('div');row.className='row ai';\n"
  "  var lbl=document.createElement('span');lbl.className='lbl';lbl.textContent='AI';\n"
  "  var t=document.createElement('div');t.className='thinking';\n"
  "  t.innerHTML='<div class=\"td\"></div><div class=\"td\"></div><div class=\"td\"></div>';\n"
  "  row.appendChild(lbl);row.appendChild(t);\n"
  "  chat.appendChild(row);chat.scrollTop=chat.scrollHeight;\n"
  "  return row;\n"
  "}\n"
  "\n"
  "function speak(t){\n"
  "  if(!window.speechSynthesis)return;\n"
  "  var plain=t.replace(/<[^>]+>/g,'').replace(/```[\\s\\S]*?```/g,'code block').slice(0,400);\n"
  "  speechSynthesis.cancel();\n"
  "  var u=new SpeechSynthesisUtterance(plain);u.rate=1.1;\n"
  "  speechSynthesis.speak(u);\n"
  "}\n"
  "\n"
  "async function send(){\n"
  "  var txt=inp.value.trim();\n"
  "  if(!txt||sbtn.disabled)return;\n"
  "  inp.value='';inp.style.height='auto';sbtn.disabled=true;\n"
  "  addRow('user',txt,false);\n"
  "  var th=showThink();\n"
  "  try{\n"
  "    var ctrl=new AbortController();\n"
  "    var timer=setTimeout(function(){ctrl.abort();},90000);\n"
  "    var r=await fetch('/api/chat',{\n"
  "      method:'POST',\n"
  "      headers:{'Content-Type':'application/json'},\n"
  "      body:JSON.stringify({message:txt}),\n"
  "      signal:ctrl.signal\n"
  "    });\n"
  "    clearTimeout(timer);\n"
  "    var d=await r.json();\n"
  "    th.remove();\n"
  "    if(d.ok){addRow('ai',md(d.reply),true);speak(d.reply);setStatus(true);}\n"
  "    else{addRow('ai','Error: '+(d.error||'unknown'),false);}\n"
  "  }catch(e){\n"
  "    th.remove();\n"
  "    addRow('ai','Connection error: '+e.message,false);\n"
  "    setStatus(false);\n"
  "  }\n"
  "  sbtn.disabled=false;inp.focus();\n"
  "}\n"
  "\n"
  "var recog=null;\n"
  "(function(){\n"
  "  var SR=window.SpeechRecognition||window.webkitSpeechRecognition;\n"
  "  if(!SR){vbtn.title='Voice not available';vbtn.style.opacity='.4';return;}\n"
  "  recog=new SR();recog.continuous=false;recog.interimResults=true;recog.lang='en-US';\n"
  "  recog.onresult=function(e){\n"
  "    var fin='',intr='';\n"
  "    for(var i=e.resultIndex;i<e.results.length;i++){\n"
  "      var tt=e.results[i][0].transcript;\n"
  "      if(e.results[i].isFinal)fin+=tt;else intr+=tt;\n"
  "    }\n"
  "    inp.value=fin||intr;\n"
  "    inp.style.height='auto';inp.style.height=Math.min(inp.scrollHeight,140)+'px';\n"
  "    if(fin){vbtn.classList.remove('rec');send();}\n"
  "  };\n"
  "  recog.onend=function(){vbtn.classList.remove('rec');};\n"
  "  recog.onerror=function(){vbtn.classList.remove('rec');};\n"
  "})();\n"
  "\n"
  "vbtn.addEventListener('click',function(){\n"
  "  if(!recog)return;\n"
  "  if(vbtn.classList.contains('rec')){recog.stop();}\n"
  "  else{recog.start();vbtn.classList.add('rec');}\n"
  "});\n"
  "\n"
  "inp.focus();\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
